name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
          include-prerelease: true
      - name: Publish .NET Core Project
        run: dotnet publish ./src/SSW.FireEmoji.WebApp/SSW.FireEmoji.WebApp.csproj -c Release -o release --nologo
      - name: copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html
      - name: Add CNAME file
        run: |
          touch CNAME
          echo "fireemoji.io" > CNAME
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot