name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore src/SSW.FireEmoji.WebApp
      - name: Build
        run: dotnet build src/SSW.FireEmoji.WebApp --no-restore
      - name: Test
        run: dotnet test src/SSW.FireEmoji.WebApp --no-build --verbosity normal
